name: Lint + Tests
on:
  pull_request:
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: ./node_modules/.bin/eslint .

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Install headless browser
        run: npx playwright install --with-deps chromium
      - name: run unit tests
        run: npm run test-ci
      - name: run e2e test
        run: npm run e2e
